---
title: "Interactive Data Map"
output: html_notebook
---

```{r}
library(tidyverse)
library(stringr)

arrest_tab <- read_csv("http://www.hcbravo.org/IntroDataSci/misc/BPD_Arrests.csv")
dat <- arrest_tab %>% 
  filter(!is.na(`Location 1`)) %>%
  separate(`Location 1`, c("lat","lng"), sep=",") %>%
  mutate(lat=as.numeric(str_replace(lat, "\\(", ""))) %>%
  mutate(lng=as.numeric(str_replace(lng, "\\)", ""))) %>%
  sample_n(2000)
dat
```

So what I did is I embedded circles with colors to indicate sex. Red circles represent crimes
peroptrated by males, yellow circles represent crimes committed by females.

```{r}
library(leaflet)

# Create a palette that maps factor levels to colors
pal <- colorFactor(c("yellow", "red"), domain = c("M", "F"))

balto_map <- leaflet(dat) %>%
  addTiles() %>%
  addCircleMarkers(
    ~lng, 
    ~lat, 
    radius=10,
    color=~pal(sex),
    stroke=F,
    fillOpacity = 0.5,
    popup=~chargeDescription, 
    label=~incidentLocation,
    clusterOptions = markerClusterOptions()
    ) %>% 
  setView(lat=39.29, lng=-76.61, zoom=11)
balto_map
```
